# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f88268fdaa6c24d040cf42b915a2ef7f1a9c30dd6203e5ba70503afe7b716c0589f1c694bba1f08cbf5761da9603136fe4a46dc5f3c8c8be4689a8ee42eaa76

test:
  secret_key_base: caa5aa08e66d509cc7407887066938d099d2a31de9e464fe3efe23d8b5760571760a9d8d4e27354f27cd6faa4a2235833e888d47ad0043c305a0266efe59df5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
