class CreateInitialForms < ActiveRecord::Migration[5.0]
  def change
    create_table :initial_forms do |t|
      t.references :user	
      t.string 	'legal_id'
      t.string 	'tec_id'
      t.string 	'name'
      t.string 	'carreer'
      t.date   	'start_year' # se puede eliminar con el carnet
      t.string 	'gender'
      t.date 	'birth_date'
      t.string 	'workplace'
      t.string 	'study_address' 
      t.string 	'father_name'
      t.string 	'mother_name'
      t.string 	'home_address'
      t.string    'accident_name'
      t.string 	'accident_telephone'
      t.string 	'accident_comment'
      t.string 	'accident_address'
      t.boolean   'team_history'
      t.boolean   'team_accomplishments'
      t.string    'semester'
      t.string    'current_year'
      t.integer   'height_cm'
      t.integer   'weight'
      t.string    'doctor_name'
      t.string    'blood_type'
      t.boolean   'deasease'
      t.boolean   'hospitalized'
      t.boolean   'surgery'
      t.boolean   'meds'
      t.boolean   'vitamins'
      t.boolean   'allergies'
      t.boolean   'bruises'
      t.boolean   'faints'
      t.boolean   'dizziness'
      t.boolean   'chestpain'
      t.boolean   'headeache'
      t.boolean   'cholesterol'
      t.boolean   'heart_studies'
      t.boolean   'heartattack_related'
      t.boolean   'skin_problems'
      t.boolean   'concussion'
      t.boolean   'memory_loss'
      t.boolean   'convulsions'
      t.boolean   'tingles'
      t.boolean   'cough'
      t.boolean   'eye_problems'
      t.boolean   'sprains'
      t.boolean   'diabetes'
      t.boolean   'pregnant'
      t.timestamps
    end
  end
end
